name: Deploy
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    environment: production
    steps:
    - name: Use variables
      run: |
        echo "OPENAI_API_KEY variable : $OPENAI_API_KEY"
        echo "SUPABASE_URL variable : $SUPABASE_URL"
        echo "SUPABASE_KEY variable : $SUPABASE_KEY"
        echo "SUPABASE_USER variable  : $SUPABASE_USER"
        echo "SUPABASE_PASS variable : $SUPABASE_PASS"
        echo "SUPABASE_TOKEN variable : $SUPABASE_TOKEN"
      env:
        OPENAI_API_KEY: ${{ vars.OPENAI_API_KEY }}
        SUPABASE_URL: ${{ vars.SUPABASE_URL }}
        SUPABASE_KEY: ${{ vars.SUPABASE_KEY }}
        SUPABASE_USER: ${{ vars.SUPABASE_USER }}
        SUPABASE_PASS: ${{ vars.SUPABASE_PASS }}
        SUPABASE_TOKEN: ${{ vars.SUPABASE_TOKEN }}


    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: check env 
        run: "env"

      - name: Install step
        run: "deno install"

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "chanwit-y-dictionary-25"
          entrypoint: "main.ts"
          root: ""
          
          
